name: fast_immutable_collections_benchmarks
description: >-
  An isolated package for benchmarking the `fast_immutable_collections` package.
version: 0.0.1
author: Philippe Fanaro

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  benchmark_harness: ^1.0.5
  meta: ^1.2.3
  path: ^1.7.0

  built_collection: ^4.3.2
  kt_dart: ^0.7.0+1
  # Depends on much older versions of Dart: `>=0.8.10+6 <2.0.0`,
  # So its use will be postponed.
  # vacuum_persistent:
  #   git:
  #     url: https://github.com/vacuumlabs/persistent

  fast_immutable_collections:
    path: ../

dev_dependencies:
  test: ^1.15.3
