name: fast_immutable_collections_example
description: The example project for the `fast_immutable_collections` package.
version: 0.0.1
authors:
  - Philippe Fanaro <philippefanaro@gmail.com>
  - glasberg.dev
  - Marcelo Glasberg

environment:
  flutter: ">=1.17.0 <1.24.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fast_immutable_collections_benchmarks:
    path: ../

dev_dependencies:
  pedantic: ^1.9.2