name: fast_immutable_collections_benchmarks
description: An isolated package for benchmarking the `fast_immutable_collections` package.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  benchmark_harness: ^2.0.0
  meta: ^1.2.3
  path: ^1.7.0

  built_collection: ^5.0.0
  kt_dart: ^0.9.0-nullsafety.0
  # Depends on much older versions of Dart: `>=0.8.10+6 <2.0.0`,
  # So its use will be either postponed or rejected entirely.
  # vacuum_persistent:
  #   git:
  #     url: https://github.com/vacuumlabs/persistent

  fast_immutable_collections:
    path: ../../

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
