name: fast_immutable_collections_benchmarks
description: An isolated package for benchmarking the `fast_immutable_collections` package.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  benchmark_harness: ^2.0.0
  meta: ^1.2.3
  path: ^1.8.0

  built_collection: ^5.0.0
  kt_dart: ^0.9.0

  fast_immutable_collections:
    path: ../../

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
