name: fast_immutable_collections
description: Immutable lists, sets, maps, and multimaps, which are as fast as their native mutable counterparts. Extension methods and comparators for native Dart collections.
version: 1.0.2
homepage: https://github.com/marcglasberg/fast_immutable_collections

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.14.13
  meta: ^1.2.4

dev_dependencies:
  intl: ^0.16.1
  matcher: ^0.12.9
  path: ^1.7.0
  pedantic: ^1.9.2
  test: ^1.15.3

  built_collection: ^4.3.2
  kt_dart: ^0.7.0+1

  benchmark_harness: ^1.0.5
  charts_flutter: ^0.9.0

  fast_immutable_collections_benchmarks:
    path: benchmark/

  # Only for CI and test coverage purposes.
  # Though you might need to test through `flutter test` instead of `pub run test`.
  flutter_test:
    sdk: flutter
