name: fast_immutable_collections
description: >-
  Immutable lists and other collections, 
  which are as fast as their native Flutter mutable counterparts.
version: 0.0.1
author: Marcelo Glasberg
homepage: glasberg.dev

environment:
  sdk: ">=2.8.0 <3.0.0"

dev_dependencies:
  benchmark_harness: ^1.0.5
  meta: ^1.2.3
  path: ^1.7.0
  pedantic: ^1.9.2
  test: ^1.15.3

  built_collection: ^4.3.2
  kt_dart: ^0.7.0+1

  # Depends on much older versions of Dart: `>=0.8.10+6 <2.0.0`,
  # So its use will be postponed.
  # vacuum_persistent:
  #   git:
  #     url: https://github.com/vacuumlabs/persistent
