name: fast_immutable_collections
description: Immutable lists and other collections, which are as fast as their native Dart/Flutter mutable counterparts.
version: 0.0.1
author: Marcelo Glasberg
homepage: glasberg.dev

environment:
  sdk: ">=2.8.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
