name: fast_immutable_collections
description: Immutable lists and other collections, which are as fast as their native Flutter mutable counterparts.
version: 0.0.1
author: Marcelo Glasberg
homepage: glasberg.dev

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
