name: fast_immutable_collections
description: Immutable lists, sets, maps, and multimaps, which are as fast as their native mutable counterparts. Extension methods and comparators for native Dart collections.
version: 1.0.0
homepage: glasberg.dev
authors:
  - glasberg.dev
  - Marcelo Glasberg
  - Philippe Fanaro <philippefanaro@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3

  # Only for CI and test coverage purposes.
  # Though you might need to test through `flutter test` instead of `pub run test`.
  flutter_test:
    sdk: flutter
