name: fast_immutable_collections
description: Immutable lists, sets, maps, and multimaps, which are as fast as their native mutable counterparts. Extension methods and comparators for native Dart collections.
version: 1.0.19
homepage: https://github.com/marcglasberg/fast_immutable_collections

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  collection: ^1.14.13
  meta: ^1.2.4

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3

  # 1) From the benchmark package

  benchmark_harness: ^1.0.5
  path: ^1.7.0

  built_collection: ^4.3.2
  kt_dart: ^0.7.0+1

  fast_immutable_collections_benchmarks:
    path: benchmark/

  # 2) From the benchmark app

  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter

  charts_flutter: ^0.9.0
  intl: ^0.16.1
