name: benchmark_app
description: The example project for the fast_immutable_collections package.
version: 0.0.1

environment:
  flutter: ">=1.17.0 <=1.25.0"
  sdk: ">=2.7.0 <3.0.0"

publish_to: none

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter

  charts_flutter: ^0.9.0
  intl: ^0.16.1

  fast_immutable_collections_benchmarks:
    path: ../

dev_dependencies:
  pedantic: ^1.9.2
