name: Dart || Tests | Formatting | Analyzer

on:
  - push
  - pull_request

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-18.04

    container:
      image: google/dart:2.10

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Run tests for coverage
        run: bash tool/run_coverage_locally.sh

      - name: Upload Results to Codecov.io
        run: bash tool/codecov.sh
