name: Dart || Tests | Formatting | Analyzer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter

    steps:
      - uses: actions/checkout@v2
      - name: Adding Flutter as a Dev Dependency
        run: |
          echo '\n' >> pubspec.yaml
          echo '  flutter_test:\n' >> pubspec.yaml
          echo '    sdk:  flutter' >> pubspec.yaml
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter run test --coverage --coverage-path=lcov.info
      - name: Upload Results to Codecov.io
        run: bash <(curl -s https://codecov.io/bash)
      - name: Formattting
        run: dartfmt -l 100 -n --set-exit-if-changed .
      - name: Static Analysis
        run: dartanalyzer --fatal-infos --fatal-warnings .