name: Dart || Tests | Formatting | Analyzer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: CI

    timeout-minutes: 10
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Run tests for coverage
        run: bash tool/run_coverage_locally.sh

      - name: Upload Results to Codecov.io
        run: bash tool/codecov.sh
